# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'jsonTypicodePosts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for jsonTypicodePosts
  pod 'Alamofire', '~> 5.1'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'ReachabilitySwift'
  pod 'Toast-Swift', '~> 5.0.1'


  target 'jsonTypicodePostsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'jsonTypicodePostsUITests' do
    # Pods for testing
  end

end
